### ISSUE TITLE
Recorder fails to capture UI layers

### ISSUE THREAD

**Issue by noisecrime** [Unity-Technologies/GenericFrameRecorder#11] opened 2017-07-18 09:49 UTC
I assume this is a known issue, but I couldn't find anything mentioned but currently the recorder will not record UI layers with 'Command Buffered Camera' Generator. 

Was unable to try other 'Offscreen Rendering' generator as it claims that there is no camera rendering. Granted the project is a complex recursive portal rendering system, but while the main camera doesn't perform any direct rendering its OnPreCull, onPreRender and OnPostRender as well as image effects are applied.  Not sure if this is a bug or just how 'Offscreen Rendering' needs to work and its not compatible with my rendering system.

Point being that UI layers need to be rendered via 'Command Buffered Camera'.

**Comment by jasonm-unity** [comment] 2017-07-18 20:08
yes, at the moment, UI is not supported. this should come with the 2017.3 release or there abouts.

**Comment by jasonm-unity** [comment] 2017-09-09 01:06
available as of v0.2

**Comment by JacobSmaga** [comment] 2017-09-09 13:33
Looks like it's bugged (?)

This is how my frame looks like in Editor:
![8021173722bbe3009264efe26214892b](https://user-images.githubusercontent.com/11807714/30240624-2e524290-9574-11e7-8a04-36c6094d53aa.png)


And how in the recording file:
![12cc0e227b10be555b31a75e2560e0ff](https://user-images.githubusercontent.com/11807714/30240625-30ac4072-9574-11e7-954b-a5073e3a79d5.png)

**Comment by jasonm-unity** [comment] 2017-09-11 20:17
can you provide a sample project that reproduces this issue? That would help enormously!

**Comment by JacobSmaga** [comment] 2017-09-12 13:37
Here is repo project: https://www.dropbox.com/s/qru9svqn5wd26wx/Recorder%20bug.rar?dl=0

Note: I think that this bug has something to do with Canvas Scale Mode.

Also in the project folder i put 10 seconds 720p recording which shows the bug.

**Comment by jasonm-unity** [comment] 2017-09-12 20:59
excellent! I can repro it. 
Looks like it a camera render order issue.

**Comment by jasonm-unity** [comment] 2017-09-19 20:22
fixed in latest v.02 release

**Comment by JacobSmaga** [comment] 2017-09-19 20:29
Great! Post can be closed.

**Closed** 2017-09-20 21:00 UTC

**Comment by Berns-s** [comment] 2022-10-30 19:32
I switched to Free Aspect in the game view and set it to stereo and then my canvas elements were showing again.
