### ISSUE TITLE
Switching recorders trashes your settings

### ISSUE THREAD

**Issue by mjmvisser** [Unity-Technologies/GenericFrameRecorder#28] opened 2017-08-29 20:58 UTC
This is painful - if you set up a recording, then realize you want video instead of frames you lose all of your settings.

**Comment by jasonm-unity** [comment] 2017-09-01 20:25
duplicate of https://github.com/Unity-Technologies/GenericFrameRecorder/issues/24 (see down the list)

**Closed** 2017-09-01 20:25 UTC
Labels: duplicate
